### PR TITLE
fix socket typos, additional tweaks

### PR DESCRIPTION
**Pull request by catfact**
- typo make initial attack time variable not work
- amplitude envelope wasn't applied!
- make `dronePath` class variable for `DroneCaster`, for easier off-norns use
- make `caster` engine variable readable, for easier off-norns use

### CODE REVIEW

**Comment by ryanlaws** [comment]
Awesome. As long as you're in here, maybe we should fix the `Env.asr` curve as well (`Dronecaster_SynthSocket.sc` L29)? Looks like it defaults to `-4` - linear crossfade probably makes more sense, yeah?

**Comment by catfact** [comment]
it's not a crossfade though; it's a fade-out plus a fade-in. (so that there is only ever one drone synth running at a time, not blowing up the CPU with 2x heavy drones.) `\sine` might be the nicest option really.

PS a `\welch` might be most appropriate if it were a crossfade (yielding equal power for un-correlated inputs.)

but sure, plenty of other things to clean up in there... lots of dumb prints...

**Comment by ryanlaws** [comment]
I'm good with `\sine` or `\welch` or even `-4`, just wanted to check whether that was the intent. However much clean up you want to do is fine with me.

**Comment by ryanlaws** [comment]
My norns is on the fritz at the moment so I can't test, but I'd be good with merging this as-is unless anyone else wants to test it first. Cleanup could be done separately.

**Review by ryanlaws — APPROVED** [review]

**Pull request merged**
