### PR TITLE
zebra breaks everything

### PR DESCRIPTION
**Pull request by catfact**
two changes really.

--------

caveats:

- this may be too presumptuous and probably needs a little work, but opening early in case you want to try it.

- i've not yet actually tested this on norns hardware. the new synths may be too heavy. 

---------

1) refactor existing code

`NodeProxy` is a helpful class purpose-made for switching out arbitrary synthdef functions in a running node (amongst other things.) i rewrote the dronecaster kernel to use a `NodeProxy` instead of manually managing a `Group`, `Synth` etc. 

this allows us to easily crossfade between drones, and to apply lag times to controls without having to add them explicitly in the synthdef functions, it's more idiomatic and harder to mess up.

however! functions wrapped in `NodeProxy` should not use an `Out` ugen directly, nor declare an `out` argument. (the `NodeProxy` adds these and uses them for xfading, chaining and so on.)

so, i lightly modified the existing drone scripts.

-------------

2) added five drone routines. these are all pretty heavy, but i think they should be OK. if its too much for norns it is easy to lower the voice counts, etc.

### CODE REVIEW

**Comment by tyleretters** [comment]
these sound awesome. very rich timbres. i love them.

- hz and amp work on all 5
- refactor appears to not have introduced any regression - old drones still work
- there is a regular periodic clicking artifact on `unbatteredtinmind.scd` that i'm pretty sure is un-inentional.
- please choose shorter file names for each:

qc

**Comment by catfact** [comment]
re:  names, ok

re: artifact:hm, i'll check. there are some soft discontinuities possibe in that one when `CombL` is modulated. i didn't find them objectionable. maybe this is a different thing (underruns.)

re: refactor:

realized one issue with the refactor: `NodeProxy`'s crossfade behavior is: if a new source is requested while a crossfade is being performed, an additional fade is started simultaneously. this is kind of bad because there is no upper limit to the number of simultaneous synths allocated this way. since the synt hfunctions can be arbitrarily heavy, and in particular can allocate a lot of server-side memory (via e.g. `DelayN`), it is easy to run into CPU overrage (causing underruns), or a failed allocation error (which is bad when it happens on the server - can kill audio or even crash i think.)

if the crossfade is desirable i can make a more focused xfade wapper class than NodeProxy, which queues a single xfade (and replpace the queued function if it exists.) it's straightforward but a bit of work.

**Comment by catfact** [comment]
decided: i'll work on that wrapper. i've talked a lot about how synthdef wrapper classes can help keep give things a consistent interface and avoid repetition. maybe a good example will be helpful.

**Comment by tyleretters** [comment]
i love that direction

**Comment by tyleretters** [comment]
these sound beautiful <3

thanks for putting that work into the refactor. this is a huge improvement.

**Pull request merged**
